version: '2'

services:
  aviationmanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_PASSWORD=sdfewlrcxiv
      - DB_DATABASE=flight
    ports:
      - "80:80"

  db:
   image: daocloud.io/zjxuan/mysql-utf8
   environment:
      - MYSQL_ROOT_PASSWORD=sdfewlrcxiv
      - MYSQL_DATABASE=flight
   volumes:
      - ./db/data/:/var/lib/mysql

  redis:
    image: redis
